# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
title: Elijah's Crib
theme: no-style-please
author: Elijah Abgao # name of site's author
email: abgaoe@gmail.com # email of site's author
url: https://eloijj.github.io # root address of the site
baseurl: "" # subpath of the site, e.g. "/blog" (leave it blank "" if you're site shouldn't use a subpath)
permalink: /:slug.html
description: > # description of the site (multiple lines allowed)
  2lazy4css... @ 2021

theme_config:
  appearance: "light" # can be "light", "dark" or "auto"
  back_home_text: "Go Back" # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: true # show blog description in home page

plugins:
  - jekyll-feed
  - jekyll-seo-tag
